package io.clouddemo.storage.rest;

import javax.enterprise.context.ApplicationScoped;
import javax.inject.Inject;

import javax.ws.rs.Consumes;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.QueryParam;
import javax.ws.rs.core.MediaType;

import com.cloudant.client.api.CloudantClient;
import com.cloudant.client.api.Database;
import com.cloudant.client.api.ClientBuilder;
import com.cloudant.client.org.lightcouch.NoDocumentException;
import com.cloudant.client.api.model.Response;

import org.eclipse.microprofile.config.inject.ConfigProperty;

import java.net.MalformedURLException;
import java.net.URL;

@Path("database")
@ApplicationScoped
public class DatabaseResource {

	/***************************************************************************************************************/
	/************************************************ DATABASE CODE ************************************************/
	/***************************************************************************************************************/
	@Inject
	@ConfigProperty(name = "cloudantapikey")
	private String cloudantapikey;

	private final String DEMO_DATABASE = "cloud-app"; /* Database Name */
	private final String END_OF_LOG_STRING = "---------------------------------------------------------------------------------------";

	/* Modify databaseEndpoint to point to your Cloudant Endpoint */
	private final String databaseEndpoint = "https://4b9321a6-d76e-4e55-8dec-ee0b88021030-bluemix.cloudantnosqldb.appdomain.cloud";
	private CloudantClient cloudantClient;

	protected Database connectToDatabase(final String databaseName) {
		URL databaseURL = null;
		try {
			databaseURL = new URL(databaseEndpoint);
		} catch (MalformedURLException e) {
			e.printStackTrace();
		}

		// Connect to Cloudant account
		this.cloudantClient = ClientBuilder.url(databaseURL)
			 .iamApiKey(this.cloudantapikey)
			 .disableSSLAuthentication()
			 .build();

		// Connect to database - false means don't create the database if it doesn't already exist
		Database db = this.cloudantClient.database(databaseName, false);

		System.out.println("Connected to Cloudant database");

		return db;
	}

	/***************************************************************************************************************/
	/************************************************* REST APIS **************************************************/
	/***************************************************************************************************************/

	/**
	 * Retrieve a contact from the database using their first and last name.
	 *
	 * @param firstName The contact's first name.
	 * @param lastName The contact's last name.
	 * @return The stored JSON with the contact's info.
	 */
	@GET
    @Path("retrieve")
    @Produces(MediaType.APPLICATION_JSON)
    public String getContactFromDatabase(
		@QueryParam("first_name") final String firstName,
		@QueryParam("last_name") final String lastName
	) {
		String documentId = firstName + lastName;
		String result = "Document " + documentId + " not found";

        try {
			Database db = connectToDatabase(DEMO_DATABASE); // DATABASE_CODE
			// Find document in database
            DemoDocument document = db.find(DemoDocument.class, documentId); // DATABASE_CODE
            System.out.println("Retrieved " + documentId + " from database");

            result = document.toJson();
        } catch (NoDocumentException e) {
            e.printStackTrace();
        }

        return result;
	}

	/**
	 * Store data in the form of a DemoDocument to the database.
	 *
	 * @param document JSON data document to store to the database.
	 * @return The stored JSON or an error message.
	 */
	@POST
	@Path("store/document")
	@Consumes(MediaType.APPLICATION_JSON)
	public String addContactToDatabase(
		DemoDocument document
	) {
		String doc = document.toJson();
		String result = "Failed storing document to database";

		if (!document.isEmpty()) {
			Database db = connectToDatabase(DEMO_DATABASE); // DATABASE_CODE

			logDocument(document, "Store Document");
			/* Overides _id generated by Cloudant (this is a non-partitioned database) 
			* This way you need to make sure that, there's no duplicate _id's in the database */
			document.setFirstLastNameAsId();

			Response response = db.save(document); // DATABASE_CODE
			if (response.getError() != null) {
				System.out.println("Document store FAILED. Error message: " + response.getError());
			} else {
				result = document.toJson();
			}
		}

		return result;
	}

	/**
	 * Log the json content of a document with the specified title.
	 *
	 * @param doc The document to log.
	 * @param title The title of the log.
	 */
	private void logDocument(DemoDocument doc, String title) {
		System.out.println(title);
		System.out.println(doc.toJsonPrettyPrinting());
		System.out.println(END_OF_LOG_STRING);
	}
}
